spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_URL:localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:kishorevanam}
    password: ${SPRING_DATASOURCE_PASSWORD:kishorevanam}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        format_sql: true
    show-sql: false
  sql:
    init:
      mode: always

server:
  port: 8080

# Logging configuration
logging:
  level:
    root: INFO
    com.kish.mcdp: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

